import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar/navbar"
import Footer from "../app/components/footer/footer";
import WishlistProvider from "../Context/WishlistContext";
import CounterProvider from "../Context/CounterContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Restaurants App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WishlistProvider>
          <CounterProvider>
            <Navbar />
            <main className="flex-1">{children}</main>
                    <Toaster richColors position="top-right" />

            <Footer />
          </CounterProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}